Homework 04
Evgeniy-Pavlov/python_education pull request #4
Opened 2023-02-20 12:39 UTC by Evgeniy-Pavlov

2023-02-26 14:39 UTC, mahenzon commented on homework_04/jsonplaceholder_requests.py
> +    asyncio.get_event_loop().run_until_complete(fetch_posts_data(POSTS_DATA_URL))
можно просто `asyncio.run(fetch_posts_data(POSTS_DATA_URL))` сделать

или вообще вынести это в async main, а тут сделать только вызов этой main

2023-02-26 14:40 UTC, mahenzon commented on homework_04/main.py
> +    await session.commit()
не нужно коммитить каждого пользователя. надо сначала всех добавить в сессию, а потом сделать один коммит на всех

2023-02-26 14:40 UTC, mahenzon commented on homework_04/main.py
> +    return User
тут возвращать нужно не `User`, а `user`

2023-02-26 14:40 UTC, mahenzon commented on homework_04/main.py
> +    return Post
тут то же самое про коммит и возврат, как про пользователя

2023-02-26 14:40 UTC, mahenzon requested changes
Хорошо, но требуются правки

2023-02-26 14:53 UTC, Evgeniy-Pavlov commented on homework_04/jsonplaceholder_requests.py
> +    asyncio.get_event_loop().run_until_complete(fetch_posts_data(POSTS_DATA_URL))
По поводу такого запуска asyncio. При запуске через run постоянно вылезает RuntimeError: Event loop is closed, при чем выбор других версий пакета ситуацию не меняет. Поэтому использовал такой вариант запуска в models и main,

2023-02-27 16:27 UTC, mahenzon approved these changes

2023-02-27 16:35 UTC, merged